import '../common/styles/_global.module.scss';

export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta
        name="viewport"
        content="width=device-width, initial-scale = 1, shrink-to-fit = no"
      />
      <meta name="theme-color" content="rgb(168, 220, 255)" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
